### PR TITLE
Add two new mouse cursor images to assets

### PR DESCRIPTION
**Pull request by Thaurin**
I'm no artist, but these seem to work well. Not yet tested on Oculus Go.

### CODE REVIEW

**Comment by Thaurin** [comment]
I went ahead and tried my hand at some better mouse pointers. I haven't tried them on Oculus Go hardware yet, but in a browser they look good to me.

**Comment by Kjos** [comment]
Awesome! Thanks. That reminds me to add a license file by the way. Itll be gplv3

**Comment by Thaurin** [comment]
Tested on Oculus Go (in fact, I'm typing this while streaming) and the mouse cursors do work really well.

**Comment by Kjos** [comment]
Ah, yeah, but that's not an issue as only the website dir in assets is
compiled into the jar. But I'll add them in next commit to the other dir too

2018-05-24 23:31 GMT+02:00 Thaurin <notifications@github.com>:

**Pull request merged**
